In [1]:
import numpy as np
import pandas as pd
import datetime

import pytest

from Outcomes import outcomes
from SEIR.utils import config
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import glob, os, sys
from pathlib import Path
#import seaborn as sns
import pyarrow.parquet as pq
import click
import pyarrow as pa

import os

In [10]:
old_hpar = pq.read_table("model_output/hpar/Maryland/inference/med/2020.08.20.12:11:11.UTC/000000001.2020.08.20.12:11:11.UTC.hpar.parquet").to_pandas()
old_hpars

geoid     quantity outcome  source  value
0     51091  probability  incidH  incidI   0.35
1     51720  probability  incidH  incidI   0.35
2     51017  probability  incidH  incidI   0.35
3     51045  probability  incidH  incidI   0.35
4     42023  probability  incidH  incidI   0.35
...     ...          ...     ...     ...    ...
3245  34003        delay  incidC  incidI   7.00
3246  24031        delay  incidC  incidI   7.00
3247  51059        delay  incidC  incidI   7.00
3248  42003        delay  incidC  incidI   7.00
3249  42101        delay  incidC  incidI   7.00

[3250 rows x 5 columns]

In [12]:
old_spar = pq.read_table("model_output/spar/Maryland/inference/2020.08.20.12:11:11.UTC/000000001.2020.08.20.12:11:11.UTC.spar.parquet").to_pandas()
old_spar

value parameter
0  0.990000     alpha
1  1.010000        R0
2  0.192308     sigma
3  0.333333     gamma

In [5]:
old_snpi = pq.read_table("model_output/snpi/Maryland/inference/2020.08.20.12:11:11.UTC/000000001.2020.08.20.12:11:11.UTC.snpi.parquet").to_pandas()
old_snpi

geoid         npi_name parameter                        start_date  \
0    51720   local_variance        r0  2020-04-15,2020-05-15,2020-05-15   
1    51017   local_variance        r0             2020-04-01,2020-05-01   
2    42023   local_variance        r0  2020-04-15,2020-05-15,2020-05-15   
3    51720  local_variance2        r0                        2020-04-15   
4    42023  local_variance2        r0                        2020-04-15   
..     ...              ...       ...                               ...   
500  34003           Place2        r0             2020-04-01,2020-05-01   
501  24031           Place2        r0             2020-04-01,2020-05-01   
502  51059           Place2        r0             2020-04-01,2020-05-01   
503  42003           Place2        r0             2020-04-01,2020-05-01   
504  42101           Place2        r0             2020-04-01,2020-05-01   

                             end_date  reduction  
0    2020-04-20,2020-05-20,2020-05-20   0.452361  
1               2020-04-15,2020-05-15   0.523802  
2    2020-04-20,2020-05-20,2020-05-20   0.536732  
3                          2020-05-01   0.000000  
4                          2020-05-01   0.000000  
..                                ...        ...  
500             2020-04-15,2020-05-15   0.274067  
501             2020-04-15,2020-05-15   0.229424  
502             2020-04-15,2020-05-15   0.240798  
503             2020-04-15,2020-05-15   0.180254  
504             2020-04-15,2020-05-15   0.248069  

[505 rows x 6 columns]

# let's write shift

In [14]:
# Total Rows: 
np.shape(a)[0]

#Total Columns: 
np.shape(a)[1]


In [47]:
shp = (10, 2) # dateXplace
array = np.random.randint(0, 50, shp)
shifts =  np.random.randint(0, 3, shp)
print(array)
print(shifts)

[[28 39]
 [24 16]
 [11 24]
 [19 32]
 [ 4 30]
 [11 28]
 [35  6]
 [25  3]
 [12  3]
 [36 29]]
[[1 0]
 [2 1]
 [1 0]
 [2 2]
 [1 2]
 [0 1]
 [1 1]
 [1 2]
 [1 2]
 [1 0]]


In [51]:
def shift_multidelay(arr, shifts, fill_value=0, stoch_delay_flag = True):
    """ Shift along first (0) axis """
    result = np.zeros_like(arr)

    if (stoch_delay_flag):
        for i, row in enumerate(arr):
            for j, elem in enumerate(row):
                ## This function takes in :
                ##  - elem (int > 0)
                ##  - delay (single average delay)
                ## and outputs
                ##  - vector of fixed size where the k element stores # of people who are delayed by k
                raise ValueError("NOT SUPPORTED YET")
                #percentages = np.random.multinomial(el<fixed based on delays[i][j]>)
                #cases = diff(round(cumsum(percentages)*elem))
                #for k,case in enumerate(cases):
                #    results[i+k][j] = cases[k]
    else:
        for i, row in enumerate(arr):
            for j, elem in enumerate(row):
                if(i + shifts[i][j] < arr.shape[0]):
                    result[i+shifts[i][j]][j] += elem
    return result

In [53]:
shift_multidelay(array, shifts, stoch_delay_flag=True)

ValueError: NOT SUPPORTED YET

In [50]:
    shifts = np.array(
            [[1, 0]
            [2, 1]
            [1, 0]
            [2, 2]
            [1, 2]
            [0, 1]
            [1, 1]
            [1, 2]
            [1, 2]
            [1, 0]])

TypeError: list indices must be integers or slices, not tuple

In [81]:
b = np.repeat(a[:,np.newaxis], 5, axis = 1)
b

array([[ 2,  2,  2,  2,  2],
       [45, 45, 45, 45, 45],
       [49, 49, 49, 49, 49]])

In [84]:
"b.shapeD".lower()

'b.shaped'

In [65]:
a = np.random.randint(0, 50, 3)
a

array([ 2, 45, 49])

In [85]:
REDUCE_PARAMS = ["alpha", "r0", "gamma", "sigma"]
{param: 1 for param in REDUCE_PARAMS}

{'alpha': 1, 'r0': 1, 'gamma': 1, 'sigma': 1}

In [4]:
old_hnpi = pq.read_table("model_output/hnpi/Maryland/inference/med/2020.08.20.12:11:11.UTC/000000004.2020.08.20.12:11:11.UTC.hnpi.parquet").to_pandas()
old_hnpi

geoid   npi_name         parameter                        start_date  \
0    51720   localVar  incidh::duration  2020-04-15,2020-05-15,2020-05-15   
1    51017   localVar  incidh::duration             2020-04-01,2020-05-01   
2    42023   localVar  incidh::duration  2020-04-15,2020-05-15,2020-05-15   
3    51720  localVar2  incidh::duration                        2020-01-31   
4    42023  localVar2  incidh::duration                        2020-01-31   
..     ...        ...               ...                               ...   
250  34003   lowerAll  incidh::duration                        2020-04-15   
251  24031   lowerAll  incidh::duration                        2020-04-15   
252  51059   lowerAll  incidh::duration                        2020-04-15   
253  42003   lowerAll  incidh::duration                        2020-04-15   
254  42101   lowerAll  incidh::duration                        2020-04-15   

                             end_date  reduction  
0    2020-04-20,2020-05-20,2020-05-20   0.496555  
1               2020-04-15,2020-05-15   0.511260  
2    2020-04-20,2020-05-20,2020-05-20   0.462429  
3                          2020-10-31   0.500189  
4                          2020-10-31   0.590209  
..                                ...        ...  
250                        2020-05-01   0.816326  
251                        2020-05-01   0.123624  
252                        2020-05-01   0.718618  
253                        2020-05-01   0.705296  
254                        2020-05-01   0.118891  

[255 rows x 6 columns]